sources:
  - type: maven
    path: pom.xml
    modules:
      - integration_tests
      - jar_artifact
      - udf_coverage
  - type: maven
    path: udf-for-testing/pom.xml
    advertise: false
    modules:
      - jar_artifact
version:
  fromSource: pom.xml
excludes:
  - regex: "W-PK-CORE-151: Pom file '.*udf-for-testing.pom.xml' contains no reference to project-keeper-maven-plugin."
  - "E-PK-CORE-18: Outdated content: '.github/workflows/ci-build.yml'"
  - "E-PK-CORE-18: Outdated content: '.github/workflows/release_droid_prepare_original_checksum.yml'"
