sources:
  - type: maven
    path: pom.xml
    modules:
      - lombok
      - integration_tests
      - jar_artifact
      - udf_coverage
  - type: maven
    path: udf-for-testing/pom.xml
    advertise: false
    modules:
      - jar_artifact
version:
  fromSource: pom.xml
linkReplacements:
  - "LICENSE-exasol-script-api.txt|https://mit-license.org/"
